export default function TermsPage() {
  const sections = [
    "CAVERNIUM — GLOBAL TERMS & CONDITIONS",
    "Version 1.0",
    "Effective Date: 29 September 2026",

    "1. Eligibility and Legal Capacity\nYou must be at least 16 years old to create an account or use CAVERNIUM.\nBy creating an account or using the Service, you represent that you are at least 16 years old and legally capable of entering into these Terms under the laws applicable to you.\nWhere applicable law requires a higher minimum age, parental or guardian authorization, or any additional legal requirement for the use of the Service, that requirement will apply.\nCAVERNIUM does not knowingly permit persons under 16 years of age to create or maintain accounts. If CAVERNIUM becomes aware that an account belongs to a person under 16, it may restrict or terminate that account and take appropriate measures concerning associated personal information in accordance with applicable law.",

    "2. The CAVERNIUM Service\nCAVERNIUM is a music discovery platform intended to help users discover, listen to, rate, save, and explore music and artists.\nThe Service may include artist profiles, music uploads, streaming and playback, ratings and listening activity, recommendations, rankings, saved tracks, artist and track information, and editorial, algorithmic, community, or other discovery features.\nFeatures, functionality, and discovery mechanisms may change over time. CAVERNIUM may introduce, modify, suspend, or discontinue features where reasonably necessary to operate, improve, secure, or maintain the Service, subject to applicable law.\nNo particular feature, discovery mechanism, ranking position, recommendation, or level of exposure is guaranteed to remain available or unchanged.",

    "3. Accounts\nCertain features require an account.\nYou are responsible for providing accurate registration information, keeping account information current, protecting authentication credentials, maintaining account security, and activity occurring through your account except where unauthorized activity results from circumstances outside your reasonable control.\nYou must promptly notify CAVERNIUM if you believe your account has been accessed without authorization.\nCAVERNIUM may take reasonable security measures, including restricting account access, where necessary to protect the Service, users, or account information.\nAccounts are personal to the registered user and may not be sold, transferred, assigned, or otherwise made available to another person without CAVERNIUM's prior authorization.",

    "4. Artist Accounts and Artist Identity\nWhere an account is used to publish music or maintain an artist profile, you represent that you are the artist, authorized representative, or otherwise authorized to operate the relevant artist account; that the artist information you provide is accurate; that you will not impersonate another artist, person, organization, or entity; and that you will not create misleading artist identities intended to deceive users or manipulate discovery systems.\nYou must not register or use an artist name, profile, or identity that intentionally impersonates, misrepresents, or falsely suggests an affiliation with another artist, person, organization, or entity.\nWhere a legitimate dispute regarding an artist identity arises, CAVERNIUM may temporarily restrict or review the affected profile or Content while the matter is investigated, subject to applicable law.\nArtist names, profile information, artwork, biographies, credits, and other metadata must not intentionally mislead users regarding the identity, authorship, affiliation, or origin of Content.",

    "5. User Content\nFor purposes of these Terms, “Content” includes music, audio recordings, compositions, lyrics, vocals, performances, artwork, cover images, photographs, videos, text, artist information, metadata, credits, descriptions, ratings, comments, and other material submitted, uploaded, displayed, or otherwise made available through the Service.\nYou retain ownership of the Content that you own. CAVERNIUM does not acquire ownership of your Content merely because you upload or make it available through the Service.\nTo operate CAVERNIUM, you grant CAVERNIUM a worldwide, non-exclusive, royalty-free license to host, store, reproduce, process, transmit, stream, publicly perform or display where necessary, technically adapt, index, distribute within the Service, and make your Content available through CAVERNIUM.\nThis license is limited to purposes reasonably connected with operating the Service; providing music playback and discovery; storing and processing Content; displaying artist and track information; recommendations and discovery features; security, moderation, and technical administration; and promoting CAVERNIUM and Content through CAVERNIUM's own Service and official promotional channels.\nWhere necessary to provide the Service, CAVERNIUM may authorize service providers acting on its behalf to exercise portions of this license.\nThis license does not transfer ownership of your Content. Nothing in these Terms prevents you from continuing to use, license, distribute, or exploit your Content elsewhere, subject to rights belonging to third parties.\nThe license granted to CAVERNIUM does not authorize CAVERNIUM to sell, license, or otherwise commercially exploit your Content outside the operation, promotion, security, and legitimate administration of the Service, unless separately authorized by you or otherwise permitted by applicable law.\nFollowing removal of Content, the license may continue for the limited period reasonably necessary for technical deletion, backups, security, legal compliance, dispute resolution, or other legitimate operational purposes.",

    "5A. Statistical and Aggregated Data\nYou authorize CAVERNIUM to collect, generate, derive, analyze, use, reproduce, disclose, publish, and otherwise exploit statistical, aggregated, analytical, and performance data derived from the operation and use of the Service, including information relating to listens, ratings, saves, rankings, recommendations, engagement, discovery activity, track and artist performance, usage patterns, trends, and other Service metrics, subject to applicable law and the CAVERNIUM Privacy Policy.\nCAVERNIUM may use such data for operating, improving, analyzing, developing, securing, promoting, and commercially developing the Service, as well as for research, benchmarking, reporting, market analysis, and other legitimate business purposes.\nTo the extent data is aggregated or anonymized so that individuals are no longer identifiable, CAVERNIUM may use and disclose it for lawful purposes without obtaining additional permission, subject to applicable law.\nWhere data remains capable of identifying an individual, CAVERNIUM will process it in accordance with the CAVERNIUM Privacy Policy and applicable data protection laws.\nRights relating to aggregated or anonymized statistical data may survive account termination. This provision does not authorize CAVERNIUM to retain or use personal information in a manner prohibited by applicable data protection law.",

    "6. Your Responsibility for Uploaded Music and Other Content\nBefore uploading or making Content available through CAVERNIUM, you must have all rights, permissions, licenses, consents, and authorizations required for that use.\nDepending on the Content, this may include rights relating to sound recordings or master recordings, musical compositions, lyrics, performances, vocals, samples, interpolations, remixes, artwork, photographs, names, likenesses, trademarks, or other protected material.\nYou must not upload Content merely because you possess a copy of it. Possession of an audio file, image, recording, or other material does not by itself establish the right to upload, distribute, publicly perform, display, or otherwise use that material through CAVERNIUM.\nYou must maintain the rights, permissions, licenses, and authorizations necessary for your Content for as long as that Content remains available through CAVERNIUM. If a required right expires, is revoked, or otherwise ceases to apply, you must promptly notify CAVERNIUM and, where necessary, remove the affected Content.\nYou are responsible for any royalties, fees, payments, reporting obligations, or other amounts that may be owed to third parties in connection with your Content or its availability through CAVERNIUM, except to the extent CAVERNIUM is expressly responsible under a separate agreement or applicable law.",

    "7. Copyright and Intellectual Property\nCAVERNIUM respects copyright and other intellectual property rights.\nYou must not use the Service to upload, distribute, reproduce, or make available Content that infringes another person's intellectual property rights.\nCopyright complaints, notices, counter-notices, infringement procedures, and repeat-infringer measures are governed in greater detail by the CAVERNIUM Copyright & Intellectual Property Policy, which forms part of these Terms.\nCAVERNIUM may maintain jurisdiction-specific procedures where required or useful, including a U.S. notice-and-takedown procedure where CAVERNIUM seeks to rely on the applicable U.S. copyright safe-harbor framework. Such a procedure does not make U.S. law the general governing law of CAVERNIUM or these Terms.\nCAVERNIUM may restrict, disable access to, or remove Content in response to a valid copyright or intellectual property complaint, legal requirement, or other circumstance covered by the CAVERNIUM Copyright & Intellectual Property Policy. Such action does not by itself constitute a final determination regarding ownership or infringement.",

    "7A. CAVERNIUM Intellectual Property\nExcept for User Content and third-party materials, CAVERNIUM and its licensors retain all rights, title, and interest in and to the Service and its components, including its software, technology, source code, interface, design, visual elements, logos, trademarks, names, graphics, text, databases, compilations, algorithms, features, and other materials made available by CAVERNIUM.\nYour use of the Service does not grant you ownership or other rights in CAVERNIUM's intellectual property except for the limited right to use the Service in accordance with these Terms.\nYou may not copy, reproduce, modify, distribute, sell, license, reverse engineer, decompile, extract, exploit, or create derivative works from CAVERNIUM's proprietary materials except where expressly permitted by CAVERNIUM or required by applicable law.",

    "8. Community and Content Rules\nYour use of CAVERNIUM must comply with the CAVERNIUM Community & Content Policy, which forms part of these Terms.\nWithout limiting that Policy, you must not use the Service to upload unlawful or infringing Content; impersonate another person or artist; deceive users regarding the origin or authorship of Content; manipulate discovery systems; artificially generate listens, ratings, saves, rankings, followers, or other engagement; coordinate multiple accounts for manipulation; use bots or automated systems to manipulate Service activity; submit fraudulent or misleading information; distribute malware or malicious code; interfere with Service security or operation; abuse, threaten, or unlawfully harass other users; or use the Service for unlawful activities.\nYou must not circumvent or attempt to circumvent any restriction, suspension, termination, or other enforcement action imposed by CAVERNIUM, including by creating or using another account or artist identity for the purpose of continuing prohibited activity.",

    "9. Duplicate or Misleading Audio Uploads\nThe same audio recording must not be uploaded repeatedly under different titles, artist identities, or other misleading metadata for the purpose of creating duplicate tracks or manipulating discovery.\nA legitimate alternate version, such as a remix, live recording, alternate mix, edit, acoustic version, instrumental version, translated version, or other materially distinct recording may be permitted where the distinction is genuine and accurately described.\nFirst confirmed violation: CAVERNIUM will send a warning to the email address associated with the account and may request clarification or correction and/or remove or restrict the duplicate Content.\nSecond confirmed violation: CAVERNIUM may permanently terminate the relevant artist account and remove the artist profile and associated Content from public availability on CAVERNIUM, subject to applicable law and any mandatory review or appeal rights.\nCAVERNIUM may consider the circumstances, evidence, legitimate explanations, and applicable law before confirming a violation.",

    "10. Ratings, Listens, Saves, Rankings and Discovery Manipulation\nCAVERNIUM is designed to provide meaningful music discovery and user-generated signals. You must not artificially manipulate those signals.\nProhibited conduct includes repeatedly listening to your own tracks through other accounts to increase listen counts; submitting ratings solely to artificially increase or decrease a score; coordinating ratings with other users for manipulation; creating accounts to boost or suppress an artist or track; using automated traffic or bots to generate engagement; purchasing or exchanging artificial engagement; or manipulating rankings, recommendations, discovery systems, or other platform metrics.\nCAVERNIUM may investigate unusual or potentially fraudulent activity and may disregard, adjust, remove, or restrict activity or associated Content where reasonably necessary to protect the integrity of the Service.\nYou are also responsible for not knowingly soliciting, directing, encouraging, paying, or otherwise arranging for other persons, accounts, services, or automated systems to engage in prohibited artificial activity on your behalf.",

    "11. Artificial Intelligence and AI-Assisted Content\nCAVERNIUM permits the use of artificial intelligence and other technological tools in the creation of music and related Content, subject to accurate disclosure and compliance with applicable rights and laws.\nWhere CAVERNIUM provides fields or mechanisms for AI creation credits, you must provide accurate information regarding the use of AI in relevant aspects of the Content, including music, lyrics, vocals, artwork, or other creative elements where applicable.\nYou remain responsible for ensuring that your use of AI tools complies with the applicable terms of those tools and with all third-party rights. You must not falsely represent AI-generated or AI-assisted material as entirely human-created where CAVERNIUM requires disclosure.\nThe use of artificial intelligence or AI-assisted tools does not relieve you of responsibility for the Content you upload. You are responsible for verifying that resulting Content may lawfully be used, uploaded, distributed, displayed, and made available through the Service.",

    "12. Scraping, Text and Data Mining, and AI Training\nUnless expressly authorized by CAVERNIUM and, where applicable, the relevant rights holder, you must not use automated systems to scrape, harvest, systematically collect, reproduce, extract, text-mine, data-mine, or otherwise process Content or Service data for purposes outside the normal operation of the Service.\nThis includes using CAVERNIUM Content to build, train, fine-tune, validate, test, or operate artificial intelligence or machine-learning systems, or to create databases, datasets, archives, repositories, or similar collections outside the normal operation of the Service.\nThis restriction does not prohibit ordinary use of the Service by users, including listening to music, viewing artist profiles, or accessing information through features intentionally provided by CAVERNIUM.\nNothing in this section overrides a right that cannot lawfully be restricted under applicable law.",

    "13. Moderation and Enforcement\nCAVERNIUM may restrict, remove, disable access to, or suspend Content or accounts where reasonably necessary to enforce these Terms or related policies; protect the Service or its users; comply with applicable law or legal process; address suspected copyright or other intellectual property infringement; address fraud, manipulation, abuse, or security risks; or protect the integrity of CAVERNIUM's discovery and ranking systems.\nCAVERNIUM may apply temporary restrictions while it reviews a suspected violation, infringement, fraudulent activity, security issue, or other matter requiring investigation. Such temporary measures may remain in place for the period reasonably necessary to complete the review, subject to applicable law and any rights to notice, explanation, or appeal.\nCAVERNIUM will consider the nature, severity, frequency, evidence, and circumstances of the relevant issue when determining an appropriate response.\nWhere applicable law requires notice, specific reasons, an opportunity to contest a decision, human review, or another procedural safeguard, CAVERNIUM will provide those safeguards to the extent required.\nWhere appropriate, CAVERNIUM may maintain records of moderation actions, including affected Content or account, action taken, applicable policy, date, and appeal or review status.",

    "14. Appeals and Reviews\nWhere CAVERNIUM restricts or removes Content or takes an account enforcement action, an affected user may have a right to request review where provided by applicable law or CAVERNIUM's applicable procedures.\nCAVERNIUM may request information reasonably necessary to evaluate a review request.\nWhere an enforcement or moderation decision is made in whole or in part using automated systems, CAVERNIUM will provide human review where required by applicable law.\nCAVERNIUM may maintain or reinstate an enforcement action where the relevant violation remains established, subject to applicable law.\nNothing in this section limits any mandatory legal right of appeal, complaint, review, or dispute resolution available under applicable law.",

    "15. Third-Party Services\nCAVERNIUM may use third-party services, infrastructure providers, payment processors, analytics providers, authentication providers, storage providers, content delivery networks, or other technologies necessary to operate the Service.\nYour use of a third-party service may also be subject to that provider's separate terms and privacy policies.\nWhere CAVERNIUM uses third-party providers to process information or perform services on its behalf, CAVERNIUM will implement the contractual and technical safeguards required by applicable law.",

    "16. Privacy\nCAVERNIUM's collection, use, storage, disclosure, and other processing of personal information is governed by the CAVERNIUM Privacy Policy, which forms part of these Terms.\nThe Privacy Policy may contain jurisdiction-specific provisions where required by applicable privacy or data protection law.\nNothing in these Terms is intended to waive, exclude, or reduce rights granted by mandatory data protection or privacy laws.\nCAVERNIUM will determine and document the applicable privacy obligations for relevant processing activities and jurisdictions as required by applicable law.",

    "17. Electronic Communications and Acceptance\nBy creating an account or using CAVERNIUM, you agree that CAVERNIUM may communicate with you electronically regarding your account, security, Content, moderation actions, copyright complaints, policy updates, Service-related matters, and other communications permitted by applicable law.\nCAVERNIUM may maintain records of your acceptance of these Terms, including the applicable version, date and time of acceptance, account identifier, and other information reasonably necessary to demonstrate acceptance and maintain an audit trail, subject to applicable law and the CAVERNIUM Privacy Policy.",

    "18. Changes to These Terms\nCAVERNIUM may update these Terms from time to time.\nAdministrative, corrective, security-related, or otherwise non-material changes may take effect without advance notice where permitted by applicable law.\nMaterial changes that may significantly affect your rights or obligations will be communicated through reasonable means before they take effect where required by applicable law.\nWhere applicable law requires affirmative consent to material changes, CAVERNIUM will obtain that consent.\nThe updated version will identify its effective date. Continued use after the effective date may constitute acceptance where permitted by applicable law.",

    "19. Suspension and Termination\nYou may stop using CAVERNIUM at any time.\nCAVERNIUM may suspend or terminate an account where reasonably necessary because of a material or repeated violation of these Terms; infringement or repeated infringement of intellectual property rights; fraud or manipulation; abuse or security threats; unlawful activity; conduct that materially threatens the Service or other users; or legal requirements.\nWhere appropriate and legally permitted, CAVERNIUM may provide notice and an opportunity to address the issue before termination.\nCAVERNIUM may take immediate action where reasonably necessary to address serious security, legal, fraud, infringement, or safety concerns.\nCAVERNIUM will consider the nature, severity, frequency, and circumstances of the relevant conduct when determining an appropriate suspension or termination measure, subject to applicable law.",

    "20. Effect of Termination on Content\nFollowing account termination or Content removal, CAVERNIUM may retain limited copies of relevant information where reasonably necessary for legal compliance, copyright disputes, fraud prevention, security, backups, accounting or recordkeeping, dispute resolution, or enforcement of these Terms.\nSuch retention does not constitute continued public availability of the Content.\nCAVERNIUM may also retain records reasonably necessary to establish the history of Content, account activity, moderation actions, rights complaints, or other events occurring before termination, where such retention is permitted or required by applicable law.\nWhere applicable law grants you a right to retrieve Content that you provided or created through the Service following termination, CAVERNIUM will provide such Content in accordance with that law, subject to applicable exceptions.",

    "21. Service Availability\nCAVERNIUM aims to provide a reliable Service but does not guarantee that the Service will always be available, uninterrupted, secure, or error-free.\nThe Service may be unavailable temporarily because of maintenance, technical problems, infrastructure failures, security incidents, updates, third-party failures, or circumstances beyond CAVERNIUM's reasonable control.\nCAVERNIUM will not be responsible for interruptions, delays, failures, or unavailability caused by circumstances beyond its reasonable control, including failures of third-party infrastructure or service providers, internet or telecommunications disruptions, power outages, natural disasters, severe weather, acts of war, civil unrest, government actions, widespread cyber incidents, or other comparable events, except to the extent otherwise required by applicable law.",

    "22. No Guarantee of Discovery, Exposure, Rankings or Engagement\nCAVERNIUM does not guarantee that any artist, track, Content, rating, profile, or account will receive a particular number of listeners, ratings, saves, recommendations, rankings, followers, streams, exposure, or other engagement.\nCAVERNIUM does not guarantee any particular ranking, recommendation, placement, visibility, audience size, listen count, rating, save count, follower count, or other performance result for any artist or Content.\nDiscovery and recommendation systems may use technical, statistical, editorial, community, or other criteria that may change over time.",

    "23. Payments, Refunds and Cancellations\nWhere CAVERNIUM offers paid products, features, subscriptions, services, or other paid functionality, applicable prices, charges, billing terms, renewal terms, and cancellation procedures will be disclosed before payment.\nExcept where a refund, cancellation, withdrawal, price reduction, replacement, or other remedy is expressly required by applicable law or provided by CAVERNIUM, payments made to CAVERNIUM are non-refundable.\nCAVERNIUM will not provide refunds solely because a user changes their mind, does not use a paid feature, terminates their account, or chooses not to continue using a paid Service after purchase, except where applicable law provides otherwise.\nA refund, credit, replacement, or other appropriate remedy may be provided where a payment was incorrectly charged, where a material technical error or malfunction attributable to CAVERNIUM prevents the user from receiving the paid Service as purchased, or where the paid Service materially fails to conform to its applicable description or contractual requirements, subject to the circumstances of the case and applicable law.\nNothing in this section excludes or limits mandatory consumer rights that apply to a remote or digital service, including any statutory withdrawal, cancellation, conformity, refund, or other remedy available under applicable law.\nCancellation of a recurring paid Service will stop future charges in accordance with the applicable cancellation terms. Cancellation does not, by itself, entitle the user to a refund of amounts already paid, except where required by applicable law or expressly provided by CAVERNIUM.",

    "24. User Representations\nBy using CAVERNIUM, you represent that: (1) the information you provide is accurate to the best of your knowledge; (2) you have the authority required to use the account; (3) you have the rights necessary for Content you upload; (4) your Content does not knowingly violate applicable law or third-party rights; (5) your activity complies with these Terms and applicable CAVERNIUM policies; (6) you will not intentionally manipulate the Service; and (7) you are not subject to any agreement, obligation, or restriction that would prevent you from granting the rights and permissions required under these Terms for the Content you make available through CAVERNIUM.",

    "24A. Indemnification\nYou agree to defend, indemnify, and hold harmless CAVERNIUM and, where applicable, its officers, directors, employees, contractors, and service providers from claims, losses, liabilities, damages, costs, and reasonable expenses arising out of or relating to: (1) your violation of these Terms or applicable CAVERNIUM policies; (2) your Content; (3) your infringement or alleged infringement of third-party rights; (4) your failure to obtain required rights, permissions, licenses, or consents; or (5) your fraudulent, abusive, or unlawful conduct.\nThis indemnification obligation applies only to the extent permitted by applicable law and does not require you to indemnify CAVERNIUM for losses caused by CAVERNIUM's own unlawful conduct where such an obligation would not be enforceable.",

    "25. Disclaimer of Warranties\nTo the maximum extent permitted by applicable law, CAVERNIUM provides the Service on an “as available” and “as reasonably available” basis.\nExcept where expressly required by law, CAVERNIUM does not warrant that the Service or any Content will always be uninterrupted, error-free, accurate, complete, secure, or available.\nCAVERNIUM does not endorse, verify, or guarantee the accuracy, authenticity, legality, ownership, quality, or reliability of Content submitted by users. User-generated Content is provided by the respective uploader, who remains responsible for such Content and the rights and permissions associated with it.\nNothing in this section excludes or limits any rights, warranties, remedies, or protections that cannot lawfully be excluded or limited under applicable law.",

    "26. Limitation of Liability\nTo the maximum extent permitted by applicable law, CAVERNIUM will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from your use of, or inability to use, the Service.\nTo the maximum extent permitted by applicable law, CAVERNIUM's aggregate liability arising from the Service or these Terms will be limited to the amount permitted by applicable law and, where legally enforceable, the amount you paid to CAVERNIUM for the relevant Service during the applicable period preceding the event giving rise to the claim.\nNothing in these Terms excludes or limits liability that cannot lawfully be excluded or limited. This includes mandatory consumer rights and remedies that cannot lawfully be waived or limited.",

    "27. Mandatory Rights and Applicable Local Law\nThese Terms are intended to operate internationally.\nThey do not exclude, restrict, or waive mandatory rights, protections, remedies, or legal requirements that apply to you under applicable law.\nWhere a provision of these Terms conflicts with a mandatory rule of applicable law, that mandatory rule will prevail to the extent of the conflict.\nNothing in these Terms is intended to prevent you from exercising rights that applicable consumer protection, privacy, intellectual property, or other mandatory laws provide to you.\nIn particular, where applicable law contains mandatory rules governing cross-border consumer contracts, those rules may determine the law applicable to the consumer relationship notwithstanding the general governing-law provision below.",

    "28. Governing Law and Jurisdiction\nFor users who enter into these Terms in a business or professional capacity, and to the extent permitted by applicable law, these Terms and the contractual relationship between you and CAVERNIUM are governed by the laws of the Oriental Republic of Uruguay, excluding its conflict-of-law rules.\nFor users who are consumers, the mandatory consumer-protection and conflict-of-laws rules applicable to the consumer relationship will prevail to the extent required by applicable law. These Terms are not intended to deprive consumers of mandatory rights or protections available in the jurisdiction applicable to them.\nTo the extent permitted by applicable law, disputes arising from the non-consumer contractual relationship between you and CAVERNIUM will be submitted to the competent courts of Montevideo, Uruguay.\nNothing in this section prevents a consumer or other protected user from bringing a claim before a court, tribunal, regulatory authority, or other forum where applicable mandatory law grants the user the right to do so.",

    "29. Severability\nIf any provision of these Terms is determined to be unlawful, invalid, or unenforceable, that provision will be enforced to the maximum extent permitted by law and the remaining provisions will continue in effect.\nIf a provision is found to be invalid or unenforceable in a particular jurisdiction, that determination will apply only to the extent and in that jurisdiction, unless applicable law requires otherwise.",

    "30. No Waiver\nA failure or delay by CAVERNIUM in enforcing any provision of these Terms does not constitute a waiver of its right to enforce that provision later.\nAny waiver by CAVERNIUM of a provision or right under these Terms must be expressly stated and will apply only to the specific instance for which it is given, unless expressly stated otherwise.",

    "31. Assignment and Transfer of the Service\nYou may not assign or transfer your rights or obligations under these Terms without CAVERNIUM's prior written consent where required.\nCAVERNIUM may assign or transfer these Terms as part of a merger, acquisition, restructuring, financing, sale of assets, or transfer of the Service, subject to applicable law.\nWhere CAVERNIUM transfers the Service or substantially all of its related assets to another entity, these Terms may be assigned to that entity together with the Service, subject to applicable law. Users will be notified of such transfer where required by applicable law.",

    "32. Entire Agreement\nThese Terms, together with the CAVERNIUM Privacy Policy, Copyright & Intellectual Property Policy, Community & Content Policy, and any other policies expressly incorporated by reference, constitute the agreement between you and CAVERNIUM concerning your use of the Service.\nThe CAVERNIUM Privacy Policy, Copyright & Intellectual Property Policy, and Community & Content Policy are incorporated into these Terms by reference and form part of the agreement between you and CAVERNIUM.\nWhere a conflict exists between these Terms and a policy specifically governing a particular subject, the specific policy will control for that subject to the extent legally permitted.",

    "33. Contact\nFor general legal, Terms, policy, and privacy inquiries, contact:\nCAVERNIUM\nWebsite: https://cavernium.com\nPrivacy and legal contact: privacy@cavernium.com\nCAVERNIUM may designate separate contact channels or email addresses for general support, legal matters, privacy inquiries, copyright and intellectual property complaints, and other specific matters. Users should use the applicable contact channel where one has been designated for the relevant request.\nCopyright complaints and notices should be submitted according to the CAVERNIUM Copyright & Intellectual Property Policy.",

    "34. Language\nThese Terms may be made available in multiple languages. Where required by applicable law, the version provided to a user may be supplied in an appropriate local language.\nIf multiple language versions exist, the version required by mandatory applicable law will control for the relevant jurisdiction. Otherwise, the English version will be the controlling contractual version to the extent permitted by applicable law.\nTranslated versions are provided for convenience or to satisfy applicable legal requirements. To the extent permitted by applicable law, differences between language versions will not create different contractual rights or obligations.",

    "35. Survival\nAny provisions of these Terms that by their nature or purpose should continue after termination or expiration will survive such termination or expiration.\nThis includes, without limitation, provisions concerning intellectual property, ownership and licensing, statistical and aggregated data, payments and amounts owed, user representations, indemnification, disclaimers, limitation of liability, dispute resolution, governing law, and rights or obligations relating to events occurring before termination.",

    "36. No Agency or Partnership\nThese Terms do not create or constitute a partnership, joint venture, employment relationship, agency relationship, franchise, or other business relationship between you and CAVERNIUM.\nYou do not have authority to represent, bind, or act on behalf of CAVERNIUM unless expressly authorized in writing.\nLikewise, CAVERNIUM does not act as your agent, representative, manager, record label, publisher, distributor, or legal representative unless expressly agreed otherwise in a separate written agreement.",

    "37. No Third-Party Beneficiaries\nExcept where expressly provided otherwise in these Terms or required by applicable law, these Terms are intended solely for the benefit of you and CAVERNIUM and do not create any right for any third party to enforce any provision of these Terms.\nThis section does not affect any rights that third parties may have independently under applicable law.",

    "38. Feedback and Suggestions\nIf you provide CAVERNIUM with suggestions, ideas, comments, proposals, recommendations, or other feedback regarding the Service (“Feedback”), you grant CAVERNIUM a worldwide, perpetual, irrevocable, royalty-free, transferable, sublicensable right to use, reproduce, modify, adapt, publish, distribute, and otherwise exploit such Feedback for any lawful purpose related to CAVERNIUM, without compensation or attribution to you.\nYou acknowledge that CAVERNIUM may independently develop or use ideas or features that are similar to Feedback provided by you.\nCAVERNIUM is not required to use, acknowledge, or respond to any Feedback.",
  ];

  return (
    <main className="min-h-screen bg-black text-white">
      <div className="mx-auto max-w-4xl px-6 py-12">
        <div className="mb-10">
          <a
            href="/"
            className="font-sans text-xs font-medium uppercase tracking-wider text-[#0286DC] transition hover:text-[#5CCBFF] hover:drop-shadow-[0_0_6px_rgba(2,134,220,0.55)]"
          >
            ← Back to Home
          </a>

          <h1 className="mt-8 text-3xl font-semibold tracking-tight text-[#E8F8FF]">
            CAVERNIUM — Global Terms & Conditions
          </h1>
        </div>

        <article className="space-y-7 rounded-2xl border border-white/10 bg-[#071016]/75 p-6 shadow-[0_0_12px_rgba(0,0,0,0.25)] md:p-8">
          {sections.map((section, index) => {
            const parts = section.split("\n");
            const first = parts[0];
            const rest = parts.slice(1);
            const isHeading = /^\d+[A-Z]?\./.test(first);

            return (
              <section key={index}>
                {isHeading ? (
                  <h2 className="mb-3 text-lg font-semibold text-[#5CCBFF]">
                    {first}
                  </h2>
                ) : (
                  <p className="whitespace-pre-line text-sm leading-7 text-white/70">
                    {first}
                  </p>
                )}

                {rest.map((part, partIndex) => (
                  <p
                    key={partIndex}
                    className="mt-3 whitespace-pre-line text-sm leading-7 text-white/70"
                  >
                    {part}
                  </p>
                ))}
              </section>
            );
          })}
        </article>
      </div>
    </main>
  );
}